.PHONY: all test

all :

test :
	./01-connect-success.py
	./01-connect-invalid-protonum.py
	./01-connect-invalid-id-0.py
	./01-connect-invalid-id-30.py
	./02-subscribe-qos0.py
	./02-subscribe-qos1.py
	./02-subscribe-qos2.py
	./03-publish-qos1.py
	./03-publish-qos2.py
	./03-publish-c2b-timeout-qos2.py
	./03-publish-b2c-timeout-qos2.py
